# <center> Gradient Boosting

In [2]:
#!pip install xgboost
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

# Load the data from the CSV file
data = pd.read_csv('output.csv')

In [3]:
data.head(10)

   Month  Year  Patient_Spend  Patient_Visits
0      6  2019    1500.577555           21538
1      1  2023    2744.775831           21747
2      4  2019    2923.682351           22114
3     12  2019    2846.837265           22730
4      4  2022    3129.159907           22160
5      8  2023    4147.830452           23073
6     10  2016    2231.115844           22190
7      4  2020    1698.040731           21442
8      6  2020    3802.309438           22686
9      3  2021    2267.319782           21636

In [4]:
# Create a binary target variable, e.g., classify high spending patients (1) vs. low spending (0)
data['High_Spend'] = (data['Patient_Spend'] > 2500).astype(int)

In [5]:
data.head(10)

   Month  Year  Patient_Spend  Patient_Visits  High_Spend
0      6  2019    1500.577555           21538           0
1      1  2023    2744.775831           21747           1
2      4  2019    2923.682351           22114           1
3     12  2019    2846.837265           22730           1
4      4  2022    3129.159907           22160           1
5      8  2023    4147.830452           23073           1
6     10  2016    2231.115844           22190           0
7      4  2020    1698.040731           21442           0
8      6  2020    3802.309438           22686           1
9      3  2021    2267.319782           21636           0

In [6]:
# Separate features and target variable
X = data[['Month', 'Year', 'Patient_Spend', 'Patient_Visits']]
y = data['High_Spend']

# Step: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
# Step: Train the XGBoost Model
# Initialize the XGBClassifier
xgb_model = xgb.XGBClassifier(objective='binary:logistic', n_estimators=100, max_depth=4, random_state=42)
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [8]:
# Step: Make Predictions and Evaluate
y_pred = xgb_model.predict(X_test)

In [9]:
# Calculate accuracy and print evaluation metrics
class_report = classification_report(y_test, y_pred)
print(f"Classification Report: {class_report}")

Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00       754
           1       1.00      1.00      1.00      1246

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000