# <font color='blue'> Working with compressed corpus containing multiple csv file data <font>

## <font color='blue'> Go to webpage using url <font>

In [1]:
import webbrowser
url = "https://www.kaggle.com/datasets/zzsleepyzzz/crypto-tweets-data-and-sentiments"
webbrowser.open(url)

True

## <font color='blue'> Unzip the data folder <font>

In [2]:
#Download the data as zip file 'nft.zip' and use the code below to unzip it into 'nft' folder.

from zipfile import ZipFile #import ZipFile class from the zipfile module
import os

print (os.getcwd()) 

# Unzip the uploaded dataset
z_path = "archive.zip"
uz_folder = "nft"

# Extract the zip file
with ZipFile(z_path, 'r') as my_file: #opens the ZIP file (z_path) in read mode ('r')
    my_file.extractall(uz_folder)

# List the files in the unzipped directory to understand its structure
unzipped_files = os.listdir(uz_folder)
#unzipped_files

/Users/rajanisingh/Desktop/2026-classroom-04

## <font color='blue'> Reading a sample csv file <font>

In [3]:
import pandas as pd

# Load one of the CSV files to examine its structure
#file_path = os.path.join(uz_folder, unzipped_files[0])
file_path="nft/240209_SOL_1777.csv"
# Read data from CSV files into a DataFrame by using pd.read_csv() function.
sample = pd.read_csv(file_path)

# Display the first few rows of the dataframe to understand its structure
sample.head(6)

,username,tweet_text,tweet_raw,date,happy,angry,surprise,sad,fear,afinn,bing,sid,bertweet,bertweet_confidence
0,ShardiB2,sol probably see a trend shift to green here ...,$SOLProbably see a trend shift to green here soon,02/09/2024,0.00,0.00,0.00,0.0,1.00,0,0,0.0000,0,0.908659
1,vinsolana,mmm good job samoyedcoin i like what youre doi...,Mmm good job @samoyedcoin i like what you’re d...,02/09/2024,0.00,0.00,0.00,0.0,1.00,5,2,0.6597,1,0.986673
2,cryptophrex,sol profits most likely to flow into inj,$SOL profits most likely to flow into $INJ,12/29/2023,0.00,0.00,0.00,0.0,1.00,0,0,0.4404,0,0.944062
3,claytopians_NFT,providing value is key being clear about the ...,Providing value is key & being clear about the...,02/09/2024,0.00,0.05,0.15,0.3,0.50,4,1,0.8771,0,0.905987
4,Solmaxxi,sol is pushing for 110 remember anon this mag...,$SOL is pushing for $110.Remember anon this ma...,02/09/2024,0.38,0.12,0.38,0.0,0.12,0,1,-0.7105,0,0.627812
5,sharkdad81,pdex project is stronger than uni cake and inc...,$PDEX project is stronger than $UNI $CAKE and ...,02/09/2024,0.00,0.00,0.00,1.0,0.00,2,2,0.3818,1,0.988513

## <font color='blue'> Creating one single meta data file <font>

In [4]:
# Load all CSV files and append them into a single dataframe

# Initialize an empty list to store the DataFrames
all_data_frames = []

# Iterate over each file in unzipped_files
for f in unzipped_files:
    if f.endswith('.csv'): # Check if the file ends with '.csv'
        one_path = os.path.join(uz_folder, f)  # Construct the full path to the CSV file
        df = pd.read_csv(one_path)             # Read the CSV file into a DataFrame
        all_data_frames.append(df)             # Append the DataFrame to the list

# Concatenate all DataFrames into a single DataFrame
full_data = pd.concat(all_data_frames, ignore_index=True)
print("Single data file named 'full_data' has been created sucessfully!")


full_data.head(12)

Single data file named 'full_data' has been created sucessfully!

,username,tweet_text,tweet_raw,date,happy,angry,surprise,sad,fear,afinn,bing,sid,bertweet,bertweet_confidence,coins,exchanges
0,ShardiB2,sol probably see a trend shift to green here ...,$SOLProbably see a trend shift to green here soon,02/09/2024,0.00,0.00,0.00,0.00,1.00,0.0,0.0,0.0000,0.0,0.908659,NaN,NaN
1,vinsolana,mmm good job samoyedcoin i like what youre doi...,Mmm good job @samoyedcoin i like what you’re d...,02/09/2024,0.00,0.00,0.00,0.00,1.00,5.0,2.0,0.6597,1.0,0.986673,NaN,NaN
2,cryptophrex,sol profits most likely to flow into inj,$SOL profits most likely to flow into $INJ,12/29/2023,0.00,0.00,0.00,0.00,1.00,0.0,0.0,0.4404,0.0,0.944062,NaN,NaN
3,claytopians_NFT,providing value is key being clear about the ...,Providing value is key & being clear about the...,02/09/2024,0.00,0.05,0.15,0.30,0.50,4.0,1.0,0.8771,0.0,0.905987,NaN,NaN
4,Solmaxxi,sol is pushing for 110 remember anon this mag...,$SOL is pushing for $110.Remember anon this ma...,02/09/2024,0.38,0.12,0.38,0.00,0.12,0.0,1.0,-0.7105,0.0,0.627812,NaN,NaN
5,sharkdad81,pdex project is stronger than uni cake and inc...,$PDEX project is stronger than $UNI $CAKE and ...,02/09/2024,0.00,0.00,0.00,1.00,0.00,2.0,2.0,0.3818,1.0,0.988513,NaN,NaN
6,web3moe,to celebrate 59k followers heres a big giveawa...,To celebrate 59k+ followers here’s a big givea...,02/09/2024,0.00,0.17,0.33,0.00,0.50,5.0,2.0,0.7906,1.0,0.937607,NaN,NaN
7,yientulips,the squad cappysnft,the squad @CappysNFT,02/09/2024,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0000,0.0,0.935295,NaN,NaN
8,gr3gor14n,获得一等奖 eventspolkadotnetwork 虫洞w的空投的地址包括但不限以下...,🥰获得一等奖 - events-polkadot.network虫洞$W的空投的地址，包括但...,02/09/2024,0.00,0.00,0.00,0.00,0.00,0.0,1.0,0.0000,0.0,0.975767,NaN,NaN
9,HeteroChupalaaa,went to leh bank the other day they gave me mo...,Went to $LEH bank the other day. They gave me ...,02/09/2024,0.22,0.00,0.00,0.33,0.44,7.0,2.0,0.8176,1.0,0.988199,NaN,NaN
10,louulvs,1 this saturday 210 the next saga three kingdo...,1/This Saturday (2/10) the next Saga Three Kin...,02/09/2024,0.12,0.00,0.50,0.00,0.38,4.0,4.0,0.7783,1.0,0.802533,NaN,NaN
11,SolPacShakur,exciting news after earning 50k on tia ive dis...,🚀 Exciting news! After earning $50k on $TIA Iv...,02/09/2024,0.33,0.00,0.17,0.33,0.17,3.0,2.0,0.9143,1.0,0.973364,NaN,NaN